### ISSUE TITLE
DHCP rogue server not working.

### ISSUE THREAD

**Issue by qeef** [tomac/yersinia#12]
This bug was already reported in Kali Linux bug tracker: https://bugs.kali.org/view.php?id=1099&history=1

When `DHCP rogue server` is configured and run, it is stucked in "creting DHCP rogue server" and it does not respond to DHCP requests. We tried it with two computers only, connected over Ethernet via switch.

**Comment by aoshiken** [comment]
Please, Could you be more specific about the interface? GTK or ncurses?

**Comment by qeef** [comment]
Definitely ncurses, not sure about GTK, I think that we tested both.

**Comment by aoshiken** [comment]
Thank you so much

I've started to fix a lot of issues but I'm currently on vacation so I will take a look when I come back.

By the way, Could you make available the traffic sent from the DHCP client in pcap format?

That would be just to be sure I'm replicating the issue in a reliable way

Thanks in advance

**Comment by qeef** [comment]
I will look into it when I save some time.

**Comment by aoshiken** [comment]
I've commited some changes in my branch gtk-bugs4 fixing some bugs with this attack.
I'm not totally sure if that finally fixes the attack, anyway I will release a v0.8.0 version in just a few days with a lot of fixes including the ones.

**Comment by aoshiken** [comment]
After some tests with my x64 Linux platform the rogue server attack seems to run OK with the current 0.8.0 version.

Closing this issue, feel free to reopen if necessary
