### ISSUE TITLE
GTK interface closes on right click

### ISSUE THREAD

**Issue by digininja** [tomac/yersinia#6]
You wanted GTK issues, right click on any of the center tables and the app closes.

I've tried starting it with debug and log flags to catch what is going wrong but nothing gets logged to screen or the file.

I'm running the latest version pulled from git and built on Debian, all dependent packages are as up-to-date as Debian testing will allow.

I'll go back to the CLI version now.

**Comment by aoshiken** [comment]
@digininja : Could you try my branch gtk-bugs?

**Comment by aoshiken** [comment]
Could anyone close this issue?
Apparently it's been fixed on PR #13
