### ISSUE TITLE
GTK closes when trying to change interface

### ISSUE THREAD

**Issue by mancubus77** [tomac/yersinia#9]
I have dozen interfaces on my PC, when I try to change interfaces GTK closes. 
(yersinia:13904): Gtk-WARNING *_: gtk_menu_attach_to_widget(): menu already attached to GtkImageMenuItem
(yersinia:13904): Gtk-WARNING *_: gtk_menu_attach_to_widget(): menu already attached to GtkImageMenuItem
(yersinia:13904): Gtk-CRITICAL **: gtk_widget_ref: assertion 'GTK_IS_WIDGET (widget)' failed
) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)

any clues?

**Comment by aoshiken** [comment]
Hi,
I'm just starting to nail down a lot of issues with the GTK version, I hope I can have this one fixed in not too much time. xD

**Comment by aoshiken** [comment]
@mancubus77 I feel confident that this issue is fixed in my branch gtk-bugs

Please, let me know if that works for you

**Comment by aoshiken** [comment]
Could anyone close this issue?

Apparently it's been fixed in PR #13
